export const metadata = { title: "Startups" };

export default function StartupsPage() {
  return (
    <div className="mx-auto max-w-7xl px-6 py-16">
      <p className="eyebrow">Startup intelligence</p>
      <h1 className="mt-3 font-display text-5xl">Funding. Acquisitions. IPOs.</h1>
      <p className="mt-4 max-w-2xl text-[color:var(--muted)]">
        Track venture activity with market analysis, timelines, and industry impact generated by dedicated
        funding and VC agents.
      </p>
    </div>
  );
}
