"""Centralized permission matrix for RBAC."""

from app.core.enums import UserRole

ROLE_PERMISSIONS: dict[UserRole, set[str]] = {
    UserRole.READER: {
        "articles:read",
        "courses:read",
        "search:basic",
        "social:read",
        "newsletter:subscribe",
        "profile:self",
    },
    UserRole.CREATOR: {
        "articles:read",
        "articles:write",
        "courses:read",
        "search:basic",
        "social:read",
        "social:write",
        "newsletter:subscribe",
        "profile:self",
        "creator:dashboard",
    },
    UserRole.EDITOR: {
        "articles:read",
        "articles:write",
        "articles:moderate",
        "courses:read",
        "search:unlimited",
        "social:read",
        "social:write",
        "social:moderate",
        "newsletter:manage",
        "profile:self",
    },
    UserRole.MODERATOR: {
        "articles:read",
        "articles:moderate",
        "courses:read",
        "search:unlimited",
        "social:read",
        "social:write",
        "social:moderate",
        "community:moderate",
        "profile:self",
        "audit:read",
    },
    UserRole.ADVERTISER: {
        "articles:read",
        "courses:read",
        "search:basic",
        "ads:manage",
        "sponsored:create",
        "analytics:ads",
        "profile:self",
        "company:manage",
    },
    UserRole.BUSINESS: {
        "articles:read",
        "articles:write",
        "courses:read",
        "courses:promote",
        "search:unlimited",
        "social:read",
        "social:write",
        "ads:manage",
        "sponsored:create",
        "jobs:manage",
        "events:promote",
        "analytics:business",
        "company:manage",
        "api:access",
        "team:manage",
        "profile:self",
    },
    UserRole.ADMIN: {
        "articles:read",
        "articles:write",
        "articles:moderate",
        "courses:read",
        "courses:write",
        "courses:promote",
        "search:unlimited",
        "social:read",
        "social:write",
        "social:moderate",
        "community:moderate",
        "newsletter:manage",
        "ads:manage",
        "sponsored:create",
        "jobs:manage",
        "events:promote",
        "analytics:admin",
        "company:manage",
        "api:access",
        "team:manage",
        "users:manage",
        "agents:monitor",
        "agents:control",
        "system:health",
        "audit:read",
        "profile:self",
    },
    UserRole.SUPERADMIN: {"*"},
}


def has_permission(role: UserRole, permission: str) -> bool:
    perms = ROLE_PERMISSIONS.get(role, set())
    return "*" in perms or permission in perms
